### ISSUE TITLE
On cancel stream wasn't disposed I guess 

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#18]
@YazeedAlKhalaf On cancel was pressed, Operation was canceled on a bad state. and it says StreamController wasn't disposed.

```log
flutter: 💡  InstallingViewModel - Installation Cancelled!
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:553:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:826:13)
#2      runExecutableArguments.<anonymous closure>
package:process_run/src/process_run.dart:150
#3      runExecutableArguments.<anonymous closure>
package:process_run/src/process_run.dart:148
#4      _rootRunUnary (dart:async/zone.dart:1362:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#10     _StreamController._add (dart:async/stream_controller.dart:607:7)
#11     _StreamController.add (dart:async/stream_controller.dart:554:5)
#12     _Socket._onData (dart:io-patch/socket_patch.dart:2140:41)
#13     _rootRunUnary (dart:async/zone.dart:1370:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#19     _StreamController._add (dart:async/stream_controller.dart:607:7)
#20     _StreamController.add (dart:async/stream_controller.dart:554:5)
#21     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1676:33)
#22     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1188:14)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
Lemme know if any fix. I can't find what stream was flowing there.

**Comment by yahu1031** [comment]
#9 duplicate
