### ISSUE TITLE
Must handle onCancelPressed instance

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#9]
```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:623:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:900:13)
#2      run.<anonymous closure>
package:process_run/process_run.dart:228
#3      run.<anonymous closure>
package:process_run/process_run.dart:226
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#10     _StreamController._add (dart:async/stream_controller.dart:682:7)
#11     _StreamController.add (dart:async/stream_controller.dart:624:5)
#12     _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
#13     _rootRunUnary (dart:async/zone.dart:1206:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#19     _StreamController._add (dart:async/stream_controller.dart:682:7)
#20     _StreamController.add (dart:async/stream_controller.dart:624:5)
#21     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1505:33)
#22     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017:14)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
flutter: 💡  InstallingViewModel - Finished Download of "flutter_linux_1.22.3-stable.tar.xz" from "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.3-stable.tar.xz"
flutter: 💡  InstallingViewModel - Started Extracting of flutter_linux_1.22.3-stable.tar.xz from https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.3-stable.tar.xz
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:623:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:900:13)
#2      streamSinkWrite
package:process_run/src/shell_utils.dart:254
#3      streamSinkWriteln
package:process_run/src/shell_utils.dart:250
#4      runCmd
package:process_run/cmd_run.dart:52
#5      Shell.runExecutableArguments
package:process_run/shell.dart:270
#6      Shell.run
package:process_run/shell.dart:245
#7      _upzipDownloadedFlutterSdkForLinux
package:flutter_installer/…/scripts/linux.dart:377
<asynchronous suspension>
#8      installOnLinux
package:flutter_installer/…/scripts/linux.dart:108
<asynchronous suspension>
#9      InstallingViewModel.install
package:flutter_installer/…/installing/installing_view_model.dart:152
<asynchronous suspension>
#10     InstallingViewModel.initialize
package:flutter_installer/…/installing/installing_view_model.dart:102
<asynchronous suspension>
```

**Reproduuce the error**

* Select everything you want and click next.
* click on install.
* cancel it and check in console log.

```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:623:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:900:13)
#2      streamSinkWrite
package:process_run/src/shell_utils.dart:254
#3      streamSinkWriteln
package:process_run/src/shell_utils.dart:250
#4      Shell.cd
package:process_run/shell.dart:200
#5      Shell.pushd
package:process_run/shell.dart:209
#6      _cdToTempDirectory
package:flutter_installer/…/scripts/linux.dart:240
<asynchronous suspension>
#7      installOnLinux
package:flutter_installer/…/scripts/linux.dart:58
<asynchronous suspension>
#8      InstallingViewModel.install
package:flutter_installer/…/installing/installing_view_model.dart:152
<asynchronous suspension>
#9      InstallingViewModel.initialize
package:flutter_installer/…/installing/installing_view_model.dart:102
<asynchronous suspension>
```

If you cancel it before the download starts.

**Comment by YazeedAlKhalaf** [comment]
I did some research and this seems to be a good solution, will be trying it today and let you know

[https://stackoverflow.com/questions/55536461/flutter-unhandled-exception-bad-state-cannot-add-new-events-after-calling-clo](https://stackoverflow.com/questions/55536461/flutter-unhandled-exception-bad-state-cannot-add-new-events-after-calling-clo)

**Comment by YazeedAlKhalaf** [comment]
Error is happening because I forgot to implement the `onCancelPressed` correctly:
```dart
       return InstallingView(
          onNextPressed: () {
            setCurrentIndex(3);
          },
          onCancelPressed: () async {
            await navigateToHomeView();
          },
          userChoice: _userChoice,
        );
```

So I just need to make sure to cancel things not just change the view

**Comment by YazeedAlKhalaf** [comment]
If the issue still persists please reply to reopen the issue.
Note that the fix will be released in version `0.0.8` 🚀

**Comment by yahu1031** [comment]
@YazeedAlKhalaf sure I will just check my changes are working or not and make a PR too. i will let you know so sooner.

**Comment by YazeedAlKhalaf** [comment]
> @YazeedAlKhalaf sure I will just check my changes are working or not and make a PR too. i will let you know so sooner.

Thanks a lot 🎉

**Comment by yahu1031** [comment]
@YazeedAlKhalaf please open this issue. OnCancel still doesn't work 😢
